trigger:
- main 

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Installing Terraform..."
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform
    echo "Terraform installed."
  displayName: 'Install Terraform'


- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'lneAzure3' # Replace with the name of your Azure service connection
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az account show'  # This command verifies the Azure CLI login status

- script: |
    # Initialize Terraform
    terraform init

    # Create a Terraform plan
    terraform plan -out=tfplan

    # Apply the Terraform plan (auto-approve for non-interactive execution)
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Actions'

- task: AzureCLI@2
  displayName: 'Azure Logout'
  inputs:
    azureSubscription: '<Your Azure Service Connection Name>'  # Replace with the name of your Azure service connection
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az logout' 

- task: AzureCLI@2
  displayName: 'Azure Logout'
  inputs:
    azureSubscription: 'lneAzure3'  # Replace with the name of your Azure service connection
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az logout' 
